global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@tradingagents.com'

route:
  group_by: ['alertname', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
    - match:
        severity: warning
      receiver: 'warning-alerts'
    - match:
        service: payment
      receiver: 'payment-alerts'

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://host.docker.internal:8000/api/alerts/webhook'
        send_resolved: true

  - name: 'critical-alerts'
    email_configs:
      - to: 'admin@tradingagents.com'
        subject: '[CRITICAL] TradingAgents Alert: {{ .GroupLabels.alertname }}'
        body: |
          Alert: {{ .GroupLabels.alertname }}
          Service: {{ .GroupLabels.service }}
          Severity: {{ .GroupLabels.severity }}
          
          {{ range .Alerts }}
          Description: {{ .Annotations.description }}
          Started: {{ .StartsAt }}
          {{ end }}
        headers:
          Priority: 'high'
    webhook_configs:
      - url: 'http://host.docker.internal:8000/api/alerts/webhook'
        send_resolved: true
        http_config:
          headers:
            'X-Alert-Severity': 'critical'

  - name: 'warning-alerts'
    email_configs:
      - to: 'alerts@tradingagents.com'
        subject: '[WARNING] TradingAgents Alert: {{ .GroupLabels.alertname }}'
        body: |
          Alert: {{ .GroupLabels.alertname }}
          Service: {{ .GroupLabels.service }}
          Severity: {{ .GroupLabels.severity }}
          
          {{ range .Alerts }}
          Description: {{ .Annotations.description }}
          Started: {{ .StartsAt }}
          {{ end }}

  - name: 'payment-alerts'
    email_configs:
      - to: 'payment-team@tradingagents.com'
        subject: '[PAYMENT] TradingAgents Payment Alert: {{ .GroupLabels.alertname }}'
        body: |
          Payment System Alert: {{ .GroupLabels.alertname }}
          
          {{ range .Alerts }}
          Description: {{ .Annotations.description }}
          Started: {{ .StartsAt }}
          {{ end }}
    webhook_configs:
      - url: 'http://host.docker.internal:8000/api/alerts/payment-webhook'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service']