name: tradingagents-main
services:
  - name: tradingagents-api
    source_dir: .
    dockerfile_path: Dockerfile
    github:
      repo: RINGCHEN/TradingAgents-Production-Complete
      branch: main
      deploy_on_push: true
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-m
    routes:
      - path: /
    envs:
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: PAYUNI_MERCHANT_ID
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: PAYUNI_HASH_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: PAYUNI_HASH_IV
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: SECRET_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: JWT_SECRET
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: ENVIRONMENT
        scope: RUN_AND_BUILD_TIME
        value: production

databases:
  - name: tradingagents-db
    engine: PG
    version: "14"
    size: db-s-1vcpu-1gb

static_sites:
  - name: tradingagents-frontend
    source_dir: frontend/dist
    routes:
      - path: /
  - name: tradingagents-admin
    source_dir: frontend/dist-admin
    routes:
      - path: /admin

