global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # TradingAgents 主應用
  - job_name: 'tradingagents-app'
    static_configs:
      - targets: ['host.docker.internal:8000']
    scrape_interval: 10s
    metrics_path: '/metrics'
    params:
      format: ['prometheus']

  # GPT-OSS 推理服務 (Phase 2 新增)
  - job_name: 'gpt-oss'
    static_configs:
      - targets: ['host.docker.internal:8080']
    scrape_interval: 5s
    metrics_path: '/metrics'
    params:
      format: ['prometheus']

  # GPU 監控 (Phase 2 核心)
  - job_name: 'gpu-metrics'
    static_configs:
      - targets: ['host.docker.internal:9400']
    scrape_interval: 5s
    metrics_path: '/metrics'

  # Prometheus 自身
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter (系統指標)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 10s

  # Redis 指標
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 10s

  # PostgreSQL 指標
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 10s

  # cAdvisor (容器指標)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 10s

  # FastAPI 應用指標 (如果啟用)
  - job_name: 'fastapi-metrics'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/api/metrics'
    scrape_interval: 5s

  # Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 30s