name: Frontend Production (build + preview + manual deploy)

on:
  workflow_dispatch:
    inputs:
      deploy:
        description: "Deploy to production after preview tests pass?"
        required: false
        default: "false"

jobs:
  build-and-preview:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: TradingAgents-Production-Complete/frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install deps
        run: npm ci

      - name: Build (Vite)
        run: |
          npm run build
          if [ ! -d "dist" ]; then echo "dist not found"; exit 1; fi

      - name: Install Playwright (if config exists)
        if: ${{ hashFiles('TradingAgents-Production-Complete/frontend/playwright-simple.config.ts') != '' }}
        run: npx playwright install --with-deps

      - name: Serve dist on :3000
        run: npx http-server TradingAgents-Production-Complete/frontend/dist -p 3000 &

      - name: Run smoke tests (headless; skip if no config)
        if: ${{ hashFiles('TradingAgents-Production-Complete/frontend/playwright-simple.config.ts') != '' }}
        env:
          BASE_URL: http://localhost:3000
          CI: 'true'
        run: npx playwright test --config=TradingAgents-Production-Complete/frontend/playwright-simple.config.ts --reporter=list

  deploy-production:
    needs: build-and-preview
    if: ${{ github.event.inputs.deploy == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      - name: Auth via Service Account (if provided)
        if: ${{ secrets.FIREBASE_SERVICE_ACCOUNT != '' }}
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT" > ${HOME}/gcp.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=${HOME}/gcp.json" >> $GITHUB_ENV

      - name: Install deps and build
        working-directory: TradingAgents-Production-Complete/frontend
        run: |
          npm ci
          npm run build

      - name: Deploy to Firebase (token if present)
        working-directory: TradingAgents-Production-Complete/frontend
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          if [ -n "$FIREBASE_TOKEN" ]; then \
            firebase deploy --project ${FIREBASE_PROJECT_ID} --only hosting:main-site,hosting:admin --token "$FIREBASE_TOKEN"; \
          else \
            firebase deploy --project ${FIREBASE_PROJECT_ID} --only hosting:main-site,hosting:admin; \
          fi

