name: Frontend Production (build + preview + manual deploy)

on:
  workflow_dispatch:
    inputs:
      deploy:
        description: "Deploy to production after preview tests pass?"
        required: false
        default: "false"

jobs:
  build-and-preview:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci

      - name: Build (Vite)
        run: |
          npm run build
          if [ -d "dist" ]; then OUT_DIR=dist; elif [ -d "build" ]; then OUT_DIR=build; else echo "No dist/ or build/ output found"; exit 1; fi
          echo "Using output folder: $OUT_DIR"
          ls -la "$OUT_DIR" | head -n 50

      - name: Install Playwright (if config exists)
        if: ${{ hashFiles('frontend/playwright.config.ts') != '' }}
        run: npx playwright install --with-deps

      - name: Serve preview on :3000 (vite preview)
        run: |
          npm run preview -- --port 3000 --strictPort &
          sleep 3
          for i in {1..10}; do curl -sSf http://localhost:3000 >/dev/null && break || (echo "waiting for preview..." && sleep 2); done

      - name: Run smoke tests (stable only)
        if: ${{ hashFiles('frontend/playwright.config.ts') != '' }}
        env:
          BASE_URL: http://localhost:3000
          CI: 'true'
        run: npx playwright test tests/e2e/smoke/stable-auth-pricing.spec.ts --config=playwright.config.ts --reporter=list

  deploy-production:
    needs: build-and-preview
    if: ${{ github.event.inputs.deploy == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      - name: Display hosting targets (both configs)
        run: |
          echo "== firebase.json targets =="
          firebase target:display hosting --config firebase.json || true
          echo "
== firebase.admin.json targets =="
          firebase target:display hosting --config firebase.admin.json || true

      - name: Resolve Firebase credentials (supports TRADINGAGENTS_MAIN)
        env:
          SA_PRIMARY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          SA_ALT: ${{ secrets.TRADINGAGENTS_MAIN }}
        run: |
          if [ -n "$SA_PRIMARY" ]; then
            echo "$SA_PRIMARY" > ${HOME}/gcp.json
            echo "GOOGLE_APPLICATION_CREDENTIALS=${HOME}/gcp.json" >> $GITHUB_ENV
            echo "Using FIREBASE_SERVICE_ACCOUNT."
          elif [ -n "$SA_ALT" ]; then
            echo "$SA_ALT" > ${HOME}/gcp.json
            echo "GOOGLE_APPLICATION_CREDENTIALS=${HOME}/gcp.json" >> $GITHUB_ENV
            echo "Using TRADINGAGENTS_MAIN service account secret."
          else
            echo "No service account JSON provided; will rely on FIREBASE_TOKEN if present."
          fi

      - name: Install deps and build
        working-directory: frontend
        run: |
          npm ci
          npm run build

      - name: Deploy to Firebase (token or SA)
        working-directory: frontend
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          PROJECT_ID=${FIREBASE_PROJECT_ID:-tradingagents-main}
          echo "Deploying to project: $PROJECT_ID"

          echo "→ Deploy main-site (firebase.json)"
          firebase deploy --project "$PROJECT_ID" --config firebase.json --only hosting:main-site --non-interactive --debug

          echo "→ Deploy admin (firebase.admin.json)"
          firebase deploy --project "$PROJECT_ID" --config firebase.admin.json --only hosting:admin --non-interactive --debug